# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20180620_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
