# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_remove_user_address_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_allergy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
